# Generated by Django 2.2.28 on 2023-04-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0053_language_addendum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order', 'level'], 'verbose_name_plural': '10. Languages'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
